### ISSUE TITLE
Documentation and/or example usage

### ISSUE THREAD

**Issue by adam-arold** [valich/intellij-markdown#17]
The README is rather lacking in the details of how to use intellij-markdown. For example I can't tell whether I can use this to create an AST of a given markdown file which I can use for other purposes? The README links some files which does not look like an api and there is no reference to any programmatic api I can use.

**Comment by valich** [comment]
Hi @adam-arold,

This is indeed an issue and I've made an attempt to add some of the most basic information on the usage and available extension API. Hope that answers your particular question. Have you any more questions or you think something is not clear please don't hesitate to ask for explanation or suggest your improvements.

**Comment by adam-arold** [comment]
Perfect, thank you! I'll try this out tomorrow.

**Comment by adam-arold** [comment]
Is this library used by IntelliJ (thus the name of the lib)?

**Comment by valich** [comment]
Yes, it's used as a parser and HTML generator for [Markdown Support](https://github.com/JetBrains/intellij-plugins/tree/master/markdown) plugin.
