### ISSUE TITLE
Autolink fails in some cases

### ISSUE THREAD

**Issue by kkononov** [valich/intellij-markdown#26]
Example of input handled incorrectly:
```
JetBrains Account portal https://account.jetbrains.com
JetBrains Online Store https://www.jetbrains.com/store
```

Result:

![image](https://user-images.githubusercontent.com/2767784/42946767-7213aa54-8b74-11e8-81f8-f91464938db7.png)

**Comment by valich** [comment]
Fixed by https://github.com/valich/intellij-markdown/commit/4b12d4e6653e4e6f5e2f91a79eb90de247d1ee4c

**Comment by kkononov** [comment]
`baseURI` is set to `http://localhost:8000`
