### ISSUE TITLE
Autolink on URLs without protocol should add `//` prefix to href

### ISSUE THREAD

**Issue by kkononov** [valich/intellij-markdown#31]
This is how it works now:
![image](https://user-images.githubusercontent.com/2767784/44680361-35b09e00-aa46-11e8-9adc-afe136286e33.png)

Related info:
https://stackoverflow.com/questions/43803778/href-without-https-prefix

**Comment by kkononov** [comment]
Encountered in 0.2.0.pre-4

**Comment by valich** [comment]
Should be fixed in master and kotlin-js-clean branches, 0.2.0-pre-6 version is published.
