### ISSUE TITLE
Compatibility with IDEA is broken in master

### ISSUE THREAD

**Issue by steelart** [valich/intellij-markdown#37]
`LinkMap.Builder#normalizeDestination` now has 2 parameters but `InlineLinkGeneratingProvider#getRenderInfo` is called it with 1 parameter.

**Comment by valich** [comment]
Processing destinations is different in different types of links in markdown (this is not stated very explicitly in spec, but it's there), so I think having a mandatory parameter is OK.

IntelliJ codebase has basically a copypaste of a part of this project; normally I hope this method won't be used very often to preserve (possibly, erroneous) compatibility variant.

I'll fix the code in IntelliJ.
