### ISSUE TITLE
Some URLs are not correctly linked

### ISSUE THREAD

**Issue by kkononov** [valich/intellij-markdown#40]
Example (there's a problem with one-letter suffix, while it's OK with a longer one): 
![image](https://user-images.githubusercontent.com/2767784/70998810-306add00-20e9-11ea-8fd1-c5f382eea72e.png)

**Comment by kkononov** [comment]
One more case (underscore at the tail is not linked): 
![image](https://user-images.githubusercontent.com/2767784/76863805-28017a00-6871-11ea-9275-8c57c991611a.png)

**Comment by valich** [comment]
I've fixed the first case; the latter is not good to fix because it might fail emph syntax. In such cases using `<link>` will be needed.

**Comment by saket** [comment]
Is this related to auto-linking of URLs?

**Comment by valich** [comment]
Yes, GFM-style autolinks w/o enclosing `<>` chars
