### ISSUE TITLE
non-english text is rendered "span per word" in HTML

### ISSUE THREAD

**Issue by katepol** [valich/intellij-markdown#45]
This breaks further copying and pasting text.
![image](https://user-images.githubusercontent.com/484436/89532374-5c62dc00-d7fa-11ea-8b67-ce20f5aecb0c.png)

**Comment by katepol** [comment]
I see a test https://github.com/valich/intellij-markdown/blob/master/test/data/parser/ruby18936.txt which asserts this behavior. Could you please tell me, why?

**Comment by valich** [comment]
Files were moved, correct link: https://github.com/valich/intellij-markdown/blob/master/src/commonTest/resources/data/parser/ruby18936.txt

It was an acceptable behaviour back then. I need to either make lexers more unicode-friendly or merge tokens post-lexing.

**Comment by valich** [comment]
Fixed in `0.2.0.pre-58`
